[package]
name = "rustybrot"
version = "1.0.0"
authors = ["JSorngard"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
image = "0.23.14"

[profile.release]
lto = "fat"
codegen-units = 1
