[package]
name = "mandelrust"
version = "1.1.0"
authors = ["JSorngard"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.15"
image = "0.24.3"
rayon = "1.5.3"

[profile.release]
lto = "fat"
codegen-units = 1
