[package]
name = "mandelrust"
version = "7.2.1"
authors = ["Johanna Sörngård (jsorngard@gmail.com)"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
image = "0.24"
rayon = "1.5"
indicatif = { version = "0.16", features = ["rayon"] }
itertools = "0.10"
lazy_static = "1.4"

[dev-dependencies]
approx = "0.5"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
