[package]
name = "mandelrust"
version = "4.0.0"
authors = ["Johanna Sörngård (jsorngard@gmail.com)"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
image = "0.24"
rayon = "1.5"
indicatif = { version = "0.16", features = ["rayon"] }

[profile.release]
lto = "fat"
codegen-units = 1
