[workspace]
members = [
    "color-space",
    "mandellib",
    "mandelbrot",
    "mandelviewer",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true

[profile.coz-profiling]
inherits = "release-lto"
debug = 1
