[package]
name = "color-space"
version = "0.3.1"
edition = "2021"

[dependencies]
image = {version = "0.24", default-features = false, features = ["png"]}
lazy_static = "1.4"
multiversion = "0.7"

[dev-dependencies]
approx = "0.5"
itertools = "0.10"