[package]
name = "mandelbrot"
version = "8.0.0"
authors = ["Johanna Sörngård (jsorngard@gmail.com)"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mandellib = {path = "../mandellib"}
color-space = {path = "../color-space"}
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
criterion = {version = "0.4", features = ["html_reports"]}

[[bench]]
name = "mandelbenches"
harness = false