[package]
name = "mandelbrot"
version = "7.2.1"
edition = "2021"

[dependencies]
color-space = {path = "../color-space"}
image = "0.24"
rayon = "1.5"
indicatif = { version = "0.16", features = ["rayon"] }
itertools = "0.10"